
# This Zulu OpenJDK Dockerfile and corresponding Docker image are
# to be used solely with Java applications or Java application components
# that are being developed for deployment on Microsoft Azure or Azure Stack,
# and are not intended to be used for any other purpose.

FROM debian:buster
MAINTAINER Zulu Enterprise Container Images <azul-zulu-images@microsoft.com>

ARG ZULU_DIR=zulu-8-azure-jre-headless-tools_8.50.0.51-8.0.275-linux_musl_x64
ARG ZULU_PACK=$ZULU_DIR.tar.gz
ARG INSTALL_DIR=/usr/lib/jvm
ARG BIN_DIR=/usr/bin
ARG MAN_DIR=/usr/share/man/man1

RUN apt-get -qq update && \
    apt-get -qq -y --no-install-recommends install ca-certificates curl musl && \
    mkdir -p ${INSTALL_DIR} && \
    curl -o /tmp/${ZULU_PACK} https://repos.azul.com/azure-only/zulu/packages/zulu-8/8u275/zulu-8-azure-jre-headless-tools_8.50.0.51-8.0.275-linux_musl_x64.tar.gz && \
    tar -xf /tmp/${ZULU_PACK} -C ${INSTALL_DIR} && rm -f /tmp/${ZULU_PACK} && \
    cd ${BIN_DIR} && \
    find ${INSTALL_DIR}/${ZULU_DIR}/bin -type f -perm -a=x -exec ln -s {} . \; && \
    mkdir -p ${MAN_DIR} && \
    cd ${MAN_DIR} && \
    find ${INSTALL_DIR}/${ZULU_DIR}/man/man1 -type f -name "*.1" -exec ln -s {} . \; && \
    rm -rf /var/lib/apt/lists/* /tmp/*
ENV JAVA_HOME=/usr/lib/jvm/zulu-8-azure-jre-headless-tools_8.50.0.51-8.0.275-linux_musl_x64
