
# This Zulu OpenJDK Dockerfile and corresponding Docker image are
# to be used solely with Java applications or Java application components
# that are being developed for deployment on Microsoft Azure or Azure Stack,
# and are not intended to be used for any other purpose.

FROM mcr.microsoft.com/java/jdk:8u202-zulu-alpine AS stage1
FROM mcr.microsoft.com/java/jre-headless:8u202-zulu-alpine
MAINTAINER Zulu Enterprise Container Images <azul-zulu-images@microsoft.com>

ARG JDK_DIR=/usr/lib/jvm/zulu-8-azure-jdk_8.36.0.1-8.0.202-linux_musl_x64
ARG JRE_DIR=/usr/lib/jvm/zulu-8-azure-jre-headless_8.36.0.1-8.0.202-linux_musl_x64
COPY --from=stage1 ${JDK_DIR}/bin/jmap ${JRE_DIR}/bin
COPY --from=stage1 ${JDK_DIR}/bin/jstack ${JRE_DIR}/bin
COPY --from=stage1 ${JDK_DIR}/lib/tools.jar ${JRE_DIR}/lib
COPY --from=stage1 ${JDK_DIR}/jre/lib/amd64/libattach.so ${JRE_DIR}/lib/amd64
RUN cd /usr/bin && find ${JRE_DIR}/bin -type f -perm -a=x -exec ln -s {} . \;

ENV JAVA_HOME=${JRE_DIR}
