
# This Zulu OpenJDK Dockerfile and corresponding Docker image are
# to be used solely with Java applications or Java application components
# that are being developed for deployment on Microsoft Azure or Azure Stack,
# and are not intended to be used for any other purpose.

FROM mcr.microsoft.com/java/jre-headless:11u3-zulu-alpine AS stage1
FROM mcr.microsoft.com/java/jdk:11u3-zulu-alpine AS stage2
MAINTAINER Zulu Enterprise Container Images <azul-zulu-images@microsoft.com>

ARG INSTALL_DIR=/usr/lib/jvm
ARG JDK_DIR=${INSTALL_DIR}/zulu-11-azure-jdk_11.31.11-11.0.3-linux_musl_x64
ARG JRE_DIR=${INSTALL_DIR}/zulu-11-azure-jre-headless_11.31.11-11.0.3-linux_musl_x64
COPY --from=stage1 ${JRE_DIR} ${JRE_DIR}

RUN JRE_TOOLS_DIR=${INSTALL_DIR}/zulu-11-azure-jre-headless-tools_11.31.11-11.0.3-linux_musl_x64 && \
    JRE_MODULES=$(jimage list ${JRE_DIR}/lib/modules | grep "Module: " | sed -e "s/^Module: //" | tr '\n' ',') && \
    JRE_MODULES=${JRE_MODULES}jdk.jcmd, && \
    jlink --release-info ${JDK_DIR}/release --module-path ${JDK_DIR}/jmods --no-header-files --strip-debug --add-modules ${JRE_MODULES} --output ${JRE_TOOLS_DIR}

FROM alpine

ARG JRE_TOOLS_DIR=/usr/lib/jvm/zulu-11-azure-jre-headless-tools_11.31.11-11.0.3-linux_musl_x64
COPY --from=stage2 ${JRE_TOOLS_DIR} ${JRE_TOOLS_DIR}

RUN apk --no-cache add ca-certificates libgcc libstdc++ ttf-dejavu && \
    cd /usr/bin && find ${JRE_TOOLS_DIR}/bin -type f -perm -a=x -exec ln -s {} . \;

#    MAN_DIR=/usr/share/man/man1 && \
#    mkdir -p ${MAN_DIR} && \
#    cd ${MAN_DIR} && \
#    find ${JRE_TOOLS_DIR}/man/man1 -type f -name "*.1" -exec ln -s {} . \;

ENV JAVA_HOME=${JRE_TOOLS_DIR}
